---
title: "NEFSC multispecies model keyrun project"
output: html_document
---

 <!-- ADD LINKS BELOW, note, using the RMD link syntax will open the presentation in the same tab, which is annoying. Use the html with the "_blank" to fix that behavior -->

These pages document decisions made regarding datasets and modeling for multispecies model keyruns for Georges Bank, USA. Methods documentation and eventually draft manuscripts will be found here too. The target date for model keyrun reviews is October 2021, with all modeling results and documentation submitted by 1 September 2021.

Model "keyruns" are defined as "standardized model runs updated with recent data, producing agreed output." The ICES group WGSAM regularly reviews multispecies model keyruns using criteria found [here](https://ices-eg.github.io/wg_WGSAM/ReviewCriteria.html). 

# Data needs

<a href="https://noaa-edab.github.io/ms-keyrun/DataNeeds.html" target="_blank"> Decisions with meeting notes - 3 June 2020 </a>

## Dataset dimensions

<a href="https://noaa-edab.github.io/ms-keyrun/DatasetDimensions.html" target="_blank"> Year, season, area decisions - 8 July 2020 </a>

*   <a href="https://noaa-edab.github.io/ms-keyrun/allocateLandingsEPU.html" target="_blank"> Allocate landings to EPU - 25 Nov 2020 </a>

<a href="https://noaa-edab.github.io/ms-keyrun/SpeciesEnvDat.html" target="_blank"> Species, environment, data package decisions - 5 August 2020 </a>

<a href="https://noaa-edab.github.io/ms-keyrun/CompsDat.html" target="_blank"> Age, length, and diet composition decisions - 3 September 2020 </a>


## Dataset source and methods documentation
<a href="https://noaa-edab.github.io/ms-keyrun/GBSurveySets.html" target="_blank"> Which Georges Bank survey footprint - 4 November 2020 </a>

## Dataset descriptions and links

# Models

## Model documentation

## Model results

# Results

## Individual model keyrun results

## Overall keyrun results

